openapi: 3.0.0
info:
  title: guestbook
  version: 1.0.0

x-yc-apigateway:
  cors:
    origin: '*'
    methods: '*'
    allowedHeaders: '*'

  service_account_id: ajefabqhkuk7o3fpb208

  variables:
    function_tag:
      default: stable
      enum: [stable, canary]

paths:
  /api/version:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ed7vhdkp2c7e63nlcm
        tag: ${var.function_tag}

  /api/messages:
    get:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ed7vhdkp2c7e63nlcm
        tag: ${var.function_tag}

    post:
      x-yc-apigateway-integration:
        type: cloud_functions
        function_id: d4ed7vhdkp2c7e63nlcm
        tag: ${var.function_tag}
